application: pmi-rdr-api-test-ds
version: 1
threadsafe: true
runtime: python27
api_version: 1

handlers:
- url: /.*
  script: main.app
  
libraries:
- name: pycrypto
  version: 2.6
- name: protorpc
  version: 1.0

